spring:
  application:
    name: service-core-transaction

  config:
    import: "configserver:http://localhost:8888"

topic:
  wallet-payment-occurred: wallet.payment-occurred
  debit-card-accounts-resolved: debit-card.accounts-resolved
  transaction-updated: transaction.updated