{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "CreditResponseEvent",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "CREDIT_RESPONSE" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string", "default": "credit-service" },

    { "name": "correlationId", "type": "string" },
    { "name": "found", "type": "boolean" },

    { "name": "creditId", "type": "string" },
    { "name": "customerId", "type": "string" },
    { "name": "number", "type": "string" },
    { "name": "type", "type": "string" },
    { "name": "status", "type": "string" },
    { "name": "creditLimit", "type": "double" },
    { "name": "balance", "type": "double" },
    { "name": "availableBalance", "type": "double" },
    { "name": "overdue", "type": "boolean" }
  ]
}