{
  "type": "record",
  "name": "MovementRecordedEvent",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "fields": [
    { "name": "eventId", "type": "string" },
    { "name": "eventType", "type": "string", "default": "MOVEMENT_RECORDED" },
    { "name": "occurredAt", "type": "string" },
    { "name": "version", "type": "string", "default": "1.0" },
    { "name": "source", "type": "string", "default": "movement-service" },

    { "name": "transactionId", "type": "string" },
    { "name": "productId", "type": "string" },
    { "name": "productType", "type": "string" },
    { "name": "amount", "type": "double" },
    { "name": "movementType", "type": "string" }
  ]
}
